apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-dotnet-gitops
  description: This is GitOps manifest for test-dotnet   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=test-dotnet
    backstage.io/kubernetes-id: test-dotnet 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: chetna14manku-org/qwe345tyu-dotnet-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: chetna14manku-org.qwe345tyu-dotnet-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test-dotnet
